// BankPicker — Nordic Business Bank Data
// Note: Prices are approximate and for illustrative purposes only.
// Always verify current pricing directly with the bank.

// Bumped automatically by the "Refresh Bank Pickr data" routine (see CLAUDE-routine
// instructions in chat). Format: ISO 8601 with timezone, e.g. 2026-04-29T22:30:00+02:00.
const DATA_LAST_UPDATED = '2026-05-15T12:00:00+02:00';

const COUNTRIES = [
  { code: 'DK', name: 'Danmark', flag: 'DK', currency: 'DKK' },
  { code: 'SE', name: 'Sverige', flag: 'SE', currency: 'SEK' },
  { code: 'NO', name: 'Norge', flag: 'NO', currency: 'NOK' },
  { code: 'FI', name: 'Finland', flag: 'FI', currency: 'EUR' },
];

const ROW_GROUPS = [
  { id: 'fees', label: 'Gebyrer', rows: [
    { id: 'onboarding', label: 'Oprettelsesgebyr', tooltip: 'Engangsgebyr ved oprettelse af erhvervskonto' },
    { id: 'monthly', label: 'Månedlig pris', tooltip: 'Fast månedlig abonnementspris ekskl. moms' },
    { id: 'extra_account_fee', label: 'Konti', tooltip: 'Antal erhvervskonti inkluderet i pakken — den første er altid inkluderet i abonnementet. Pris pr. ekstra konto vises hvor det er offentligt.' },
  ]},
  { id: 'transfers', label: 'Overførsler', rows: [
    { id: 'domestic_included', label: 'Overførsler', tooltip: 'Pris per indenlandsk overførsel. Nogle pakker inkluderer et antal gratis overførsler pr. måned, derefter betales pr. stk.' },
    { id: 'intl_transfer', label: 'Udenlandske overf.', tooltip: 'Udgående overførsler til udlandet. SEPA = EUR-betaling inden for SEPA-zonen (lavt gebyr). SWIFT = alle andre valutaer/lande (højere gebyr).' },
    { id: 'fx_fee', label: 'Valutaveksling (FX)', tooltip: 'Bankens tillæg oven i markedskursen, når der veksles fra én valuta til en anden.' },
  ]},
  { id: 'cards', label: 'Kort & Betaling', rows: [
    { id: 'card_fee', label: 'Erhvervskort', tooltip: 'Hvilket erhvervskort der er inkluderet i pakken (fx Mastercard Business Debit, Visa eller firmakort).' },
    { id: 'physical_card_extra', label: 'Antal fysiske kort', tooltip: 'Antal fysiske kort der er inkluderet, samt pris pr. ekstra kort (årsgebyr eller engangsbetaling).' },
    { id: 'digital_card_extra', label: 'Antal digitale kort', tooltip: 'Antal virtuelle/digitale kort der er inkluderet i pakken.' },
    { id: 'mobilepay', label: 'MobilePay Erhverv', tooltip: 'Lokal mobilbetaling: MobilePay (DK), Swish (SE) eller Vipps (NO). Bruges til at modtage betalinger fra privatkunder uden kortterminal.' },
  ]},
  { id: 'credit', label: 'Kreditmuligheder', rows: [
    { id: 'overdraft', label: 'Kassekredit', tooltip: 'Mulighed for at trække kontoen i minus (mod rente og evt. gebyr). Renten fastsættes individuelt efter kreditvurdering.' },
    { id: 'business_loan', label: 'Erhvervslån', tooltip: 'Mulighed for lån til drift, investeringer, udstyr m.m. Renten afhænger af kreditvurdering og sikkerhedsstillelse.' },
    { id: 'credit_pricing', label: 'Typisk pris', tooltip: 'Vejledende renteinterval eller bidragssats. Eksakt pris fastsættes individuelt baseret på virksomhedens økonomi og kreditvurdering.' },
  ]},
  { id: 'support', label: 'Support', rows: [
    { id: 'support', label: 'Supporttype', tooltip: 'Tilgængelige supportkanaler (telefon, chat, e-mail, filial), åbningstider og garanteret svartid (SLA = Service Level Agreement).' },
  ]},
  { id: 'extras', label: 'Killer features', rows: [
    { id: 'killer_features', label: 'Killer features', tooltip: 'Unikke fordele.' },
  ]},
];

// Sources: official prislister from danskebank.dk, nordea.dk, revolut.com/da-DK,
// lunar.app/dk, nykredit.dk — verified 2026-04-25. See bank-data-detailed.js
// research notes for caveats (FX markups, bundle discounts, deposit guarantees).
const BANKS_DK = [
  {
    id: 'danske', name: 'Danske Bank', color: '#0E2540', logo: 'DB',
    packages: [
      { name: 'Danske Business One',
        onboarding: '1.500 kr', monthly: '139 kr', min_balance: '0 kr',
        domestic_transfer: 'Ubegrænset gratis', domestic_included: 'Ubegrænset gratis', intl_transfer: '50 kr/overf.', fx_fee: '1,0% EU / 1,5% øvrige',
        card_fee: '1 Mastercard Business Debit inkl.', physical_card_extra: '1 inkl. · ekstra 300 kr/år', digital_card_extra: 'Pris ikke offentlig', mobilepay: 'Ja',
        netbank: 'Basisnetbank', payroll: 'Via Zenegy', api: 'Ja (District)', physical_branch: 'Ja',
        support: 'Telefon, online, chat, e-mail',
                killer_features: [{"label":"Realkredit Danmark","tone":"green"},{"label":"Landsdækkende filialer","tone":"neutral"},{"label":"The Hub for startups","tone":"blue"}],
        extra_account_fee: '1 inkl.',
        overdraft: 'Ja', business_loan: 'Ja', credit_pricing: 'Renter individuelt fastsat (markeds-gns. 3,9% okt 2026). Kassekredit typisk 5-15% p.a.',
        _monthly: 139, _transfer: 0, _intl: 50, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
      { name: 'Danske Business Plus',
        onboarding: '1.500 kr', monthly: '259 kr', min_balance: '0 kr',
        domestic_transfer: '1 kr/stk', domestic_included: '1 kr/stk', intl_transfer: '50 kr/overf.', fx_fee: '1,0% EU / 1,5% øvrige',
        card_fee: '1 Mastercard Business Debit inkl.', physical_card_extra: '1 inkl. · ekstra 300 kr/år', digital_card_extra: 'Pris ikke offentlig', mobilepay: 'Ja',
        netbank: 'District netbank', payroll: 'Via Zenegy', api: 'Ja (District)', physical_branch: 'Ja',
        support: 'Telefon, online, chat, e-mail, filial',
                killer_features: [{"label":"5 erhvervskonti inkl.","tone":"blue"},{"label":"Multi-currency","tone":"blue"},{"label":"District Pro","tone":"neutral"}],
        extra_account_fee: '5 inkl. · ekstra 15 kr/md',
        overdraft: 'Ja', business_loan: 'Ja', credit_pricing: 'Renter individuelt fastsat (markeds-gns. 3,9% okt 2026). Kassekredit typisk 5-15% p.a.',
        _monthly: 259, _transfer: 1, _intl: 50, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
      { name: 'Danske Business Pro',
        onboarding: '1.500 kr', monthly: '299 kr', min_balance: '0 kr',
        domestic_transfer: '1 kr/stk', domestic_included: '1 kr/stk', intl_transfer: '50 kr/overf.', fx_fee: '1,0% EU / 1,5% øvrige',
        card_fee: 'Mastercard Corporate Gold (1.045 kr/år)', physical_card_extra: '1 Gold inkl. · ekstra 300 kr/år', digital_card_extra: 'Pris ikke offentlig', mobilepay: 'Ja',
        netbank: 'District netbank', payroll: 'Via Zenegy', api: 'Ja (District)', physical_branch: 'Ja',
        support: 'Dedikeret rådgiver',
                killer_features: [{"label":"Dedikeret rådgiver","tone":"gold"},{"label":"Frit antal konti","tone":"blue"},{"label":"Mastercard Gold","tone":"gold"},{"label":"Trade finance","tone":"neutral"}],
        extra_account_fee: 'Ubegrænset inkl.',
        overdraft: 'Ja', business_loan: 'Ja', credit_pricing: 'Renter individuelt fastsat (markeds-gns. 3,9% okt 2026). Kassekredit typisk 5-15% p.a.',
        _monthly: 299, _transfer: 1, _intl: 50, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
    ]
  },
  {
    id: 'nordea', name: 'Nordea', color: '#1100C8', logo: 'N',
    packages: [
      { name: 'Nordea Business Base',
        onboarding: '0 kr', monthly: '245 kr (75 kr m/privatbundle)', min_balance: '0 kr',
        domestic_transfer: '1,25 kr/stk', domestic_included: '1,25 kr/stk', intl_transfer: '60 kr/overf.', fx_fee: '1,17% EU / 1,99% øvrige',
        card_fee: '1 firmakort inkl.', physical_card_extra: '1 inkl. · ekstra 150 kr/år', digital_card_extra: 'Ikke understøttet', mobilepay: 'Ja',
        netbank: 'Nordea Business', payroll: 'Via partner', api: 'Ja (Nordea API Market)', physical_branch: 'Ja',
        support: 'Telefon, chat, filial (08:30–17)',
                killer_features: [{"label":"Best SME Platform 2025","tone":"gold"},{"label":"Nordisk netværk","tone":"neutral"},{"label":"Bundle 75 kr/md","tone":"green"},{"label":"0 kr oprettelse","tone":"green"}],
        extra_account_fee: '1 inkl. · ekstra 50 kr/md',
        overdraft: 'Ja', business_loan: 'Ja', credit_pricing: 'Renter individuelt fastsat (markeds-gns. 3,9% okt 2026). Kassekredit typisk 5-15% p.a.',
        _monthly: 245, _transfer: 1.25, _intl: 60, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
    ]
  },
  {
    id: 'revolut', name: 'Revolut', color: '#191C1F', logo: 'R',
    packages: [
      { name: 'Basic',
        onboarding: '0 kr', monthly: '85 kr', min_balance: '0 kr',
        domestic_transfer: '5 gratis/md · derefter 20 kr/stk', domestic_included: '5 gratis/md · derefter 20 kr/stk', intl_transfer: '20 kr/overf.', fx_fee: '0,6% (1% weekend)',
        card_fee: '1 fysisk + 200 virtuelle', physical_card_extra: '1 inkl. · ekstra 60 kr/stk', digital_card_extra: '200 inkl.', mobilepay: 'Nej',
        netbank: 'Revolut Business', payroll: '—', api: 'Nej', physical_branch: 'Nej',
        support: 'Chat 24/7',
                killer_features: [{"label":"35+ valutaer","tone":"blue"},{"label":"~10 min onboarding","tone":"green"},{"label":"Interbank FX","tone":"blue"},{"label":"24/7 support","tone":"neutral"}],
        extra_account_fee: 'Ubegrænset inkl.',
        overdraft: 'Nej', business_loan: 'Nej', credit_pricing: '—',
        _monthly: 85, _transfer: 20, _intl: 20, _hasApi: false, _hasBranch: false, _hasMobilePay: false },
      { name: 'Grow',
        onboarding: '0 kr', monthly: '260 kr', min_balance: '0 kr',
        domestic_transfer: '100 gratis/md · derefter 20 kr/stk', domestic_included: '100 gratis/md · derefter 20 kr/stk', intl_transfer: '5 gratis/md · derefter 20 kr/overf.', fx_fee: '0,6% (1% weekend)',
        card_fee: '1 metal + 200 virtuelle', physical_card_extra: '1 metal inkl. · ekstra 60 kr/stk', digital_card_extra: '200 inkl.', mobilepay: 'Nej',
        netbank: 'Revolut Business', payroll: '—', api: 'Ja', physical_branch: 'Nej',
        support: 'Chat 24/7',
                killer_features: [{"label":"100 gratis indl. overf.","tone":"blue"},{"label":"5 gratis internationale","tone":"blue"},{"label":"1 Metal-kort","tone":"gold"},{"label":"Bulk payments","tone":"neutral"},{"label":"Flexible Cash Funds","tone":"green"}],
        extra_account_fee: 'Ubegrænset inkl.',
        overdraft: 'Nej', business_loan: 'Nej', credit_pricing: '—',
        _monthly: 260, _transfer: 20, _intl: 20, _hasApi: true, _hasBranch: false, _hasMobilePay: false },
      { name: 'Scale',
        onboarding: '0 kr', monthly: '770 kr', min_balance: '0 kr',
        domestic_transfer: '1.000 gratis/md · derefter 20 kr/stk', domestic_included: '1.000 gratis/md · derefter 20 kr/stk', intl_transfer: '25 gratis/md · derefter 20 kr/overf.', fx_fee: '0,6% (1% weekend)',
        card_fee: '2 metal + ubegr. virtuelle', physical_card_extra: '2 metal inkl. · ekstra 60 kr/stk', digital_card_extra: '200 inkl.', mobilepay: 'Nej',
        netbank: 'Revolut Business', payroll: '—', api: 'Ja', physical_branch: 'Nej',
        support: 'Prioritet chat 24/7',
                killer_features: [{"label":"1.000 gratis indl. overf.","tone":"blue"},{"label":"25 gratis internationale","tone":"blue"},{"label":"2 Metal-kort","tone":"gold"},{"label":"Kort-personalisering","tone":"neutral"},{"label":"Højere FX-allowance","tone":"green"}],
        extra_account_fee: 'Ubegrænset inkl.',
        overdraft: 'Nej', business_loan: 'Nej', credit_pricing: '—',
        _monthly: 770, _transfer: 20, _intl: 20, _hasApi: true, _hasBranch: false, _hasMobilePay: false },
    ]
  },
  {
    id: 'lunar', name: 'Lunar', color: '#1EC862', logo: 'L',
    packages: [
      { name: 'Lunar Business Simple',
        onboarding: '1.495 kr', monthly: '241 kr', min_balance: '0 kr',
        domestic_transfer: '3 gratis/md · derefter 3 kr/stk', domestic_included: '3 gratis/md · derefter 3 kr/stk', intl_transfer: '50 kr/overf.', fx_fee: '0,5%',
        card_fee: '1 digitalt Visa (fysisk: 99 kr)', physical_card_extra: '99 kr/stk (engang)', digital_card_extra: '1 inkl.', mobilepay: 'Ja',
        netbank: 'Lunar app', payroll: '—', api: 'Nej', physical_branch: 'Nej',
        support: 'Chat, telefon, e-mail',
                killer_features: [{"label":"Dansk banklicens","tone":"green"},{"label":"100% digital","tone":"blue"},{"label":"Gratis CVR-oprettelse","tone":"green"},{"label":"Erhvervslån via Froda/Qred","tone":"neutral"}],
        extra_account_fee: '1 inkl. · ekstra 19 kr/md',
        overdraft: 'Nej', business_loan: 'Via Froda/Qred', credit_pricing: 'Op til 3 mio. kr. via Froda · op til 500.000 kr. via Qred. Fast rente, kreditvurdering.',
        _monthly: 241, _transfer: 3, _intl: 50, _hasApi: false, _hasBranch: false, _hasMobilePay: true },
      { name: 'Lunar Business Essential',
        onboarding: '0 kr', monthly: '366 kr', min_balance: '0 kr',
        domestic_transfer: '10 gratis/md · derefter 3 kr/stk', domestic_included: '10 gratis/md · derefter 3 kr/stk', intl_transfer: '25 kr/overf.', fx_fee: '0,5%',
        card_fee: '3 Visa-kort inkl.', physical_card_extra: '3 inkl. · ekstra 99 kr/stk', digital_card_extra: '3 inkl.', mobilepay: 'Ja',
        netbank: 'Lunar app', payroll: '—', api: 'Ja (Dinero/Billy/e-conomic)', physical_branch: 'Nej',
        support: 'Chat, telefon, e-mail',
                killer_features: [{"label":"3 konti + 3 kort","tone":"blue"},{"label":"Auto-bogføring","tone":"blue"},{"label":"Rejse + cyber-forsikring","tone":"green"},{"label":"Bulk-overførsler","tone":"neutral"}],
        extra_account_fee: '3 inkl. · ekstra 19 kr/md',
        overdraft: 'Nej', business_loan: 'Via Froda/Qred', credit_pricing: 'Op til 3 mio. kr. via Froda · op til 500.000 kr. via Qred. Fast rente, kreditvurdering.',
        _monthly: 366, _transfer: 3, _intl: 25, _hasApi: true, _hasBranch: false, _hasMobilePay: true,
        _changes: { api: { date: '2026-04-27', updateId: 14 } } }, // demo seed (Essential — detailed view); routine will overwrite
      { name: 'Lunar Business Limitless',
        onboarding: '0 kr', monthly: '491 kr', min_balance: '0 kr',
        domestic_transfer: 'Ubegrænset gratis', domestic_included: 'Ubegrænset gratis', intl_transfer: 'Kun FX-tillæg', fx_fee: '0,5%',
        card_fee: 'Ubegrænset Visa-kort', physical_card_extra: 'Ubegrænset inkl.', digital_card_extra: 'Ubegrænset inkl.', mobilepay: 'Ja',
        netbank: 'Lunar app', payroll: '—', api: 'Ja (Dinero/Billy/e-conomic)', physical_branch: 'Nej',
        support: 'Chat, telefon, e-mail (7 dage/uge)',
                killer_features: [{"label":"+0,75% rente op til 5M kr","tone":"green"},{"label":"Wolt+ inkl.","tone":"green"},{"label":"Ubegr. konti/kort/overf.","tone":"blue"},{"label":"Rejse + cyber-forsikring","tone":"neutral"},{"label":"Gratis SWIFT","tone":"green"}],
        extra_account_fee: 'Ubegrænset inkl.',
        overdraft: 'Nej', business_loan: 'Via Froda/Qred', credit_pricing: 'Op til 3 mio. kr. via Froda · op til 500.000 kr. via Qred. Fast rente, kreditvurdering.',
        _monthly: 491, _transfer: 0, _intl: 0, _hasApi: true, _hasBranch: false, _hasMobilePay: true,
        _changes: { monthly: { date: '2026-04-29', updateId: 13 } } }, // demo seed (Limitless — visible in summary); routine will overwrite
    ]
  },
  {
    id: 'nykredit', name: 'Nykredit', color: '#1E2A7F', logo: 'NK',
    packages: [
      { name: 'Nykredit Enkel',
        onboarding: '3.000 kr', monthly: '135 kr', min_balance: '0 kr',
        domestic_transfer: '20 gratis/md', domestic_included: '20 gratis/md', intl_transfer: '50 kr/overf.', fx_fee: '1,0% EU / 1,5% øvrige',
        card_fee: '1 Mastercard Business Debit inkl.', physical_card_extra: '1 inkl. · ekstra 300 kr/år', digital_card_extra: 'Ikke understøttet', mobilepay: 'Ja',
        netbank: 'MitNykredit', payroll: 'Via Bank Connect', api: 'Ja (Bank Connect)', physical_branch: 'Ja',
        support: 'Telefon, chat, lokalbank',
                killer_features: [{"label":"ErhvervsKroner program","tone":"green"},{"label":"Realkredit-rabat","tone":"green"},{"label":"Netbankforsikring","tone":"neutral"},{"label":"150+ lokalbanker","tone":"neutral"}],
        extra_account_fee: '1 inkl.',
        overdraft: 'Ja', business_loan: 'Ja', credit_pricing: 'Realkredit-bidrag fra ~1,5% p.a. · ErhvervsKroner-rabat 1.500 kr/lånt mio. kr/år (til 2027).',
        _monthly: 135, _transfer: 2, _intl: 50, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
      { name: 'Nykredit Plus',
        onboarding: '3.000 kr', monthly: '225 kr (165 kr m/boligbundle)', min_balance: '0 kr',
        domestic_transfer: '60 gratis/md', domestic_included: '60 gratis/md', intl_transfer: '50 kr/overf.', fx_fee: '1,0% EU / 1,5% øvrige',
        card_fee: '3 Mastercard Business Debit', physical_card_extra: '3 inkl. · ekstra 300 kr/år', digital_card_extra: 'Ikke understøttet', mobilepay: 'Ja',
        netbank: 'MitNykredit', payroll: 'Bank Connect', api: 'Ja (Bank Connect)', physical_branch: 'Ja',
        support: 'Telefon, chat, lokalbank',
                killer_features: [{"label":"Holding-tilvalg gratis","tone":"green"},{"label":"FI-kreditor inkl.","tone":"neutral"},{"label":"BoligBank-bundle","tone":"green"},{"label":"Realkredit-rabat","tone":"green"}],
        extra_account_fee: '3 inkl.',
        overdraft: 'Ja', business_loan: 'Ja', credit_pricing: 'Realkredit-bidrag fra ~1,5% p.a. · ErhvervsKroner-rabat 1.500 kr/lånt mio. kr/år (til 2027).',
        _monthly: 225, _transfer: 1.25, _intl: 50, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
      { name: 'Nykredit Total',
        onboarding: '3.000 kr', monthly: '385 kr', min_balance: '0 kr',
        domestic_transfer: '400 gratis/md', domestic_included: '400 gratis/md', intl_transfer: '50 kr/overf.', fx_fee: '1,0% EU / 1,5% øvrige',
        card_fee: '10 Mastercard Business Debit', physical_card_extra: '10 inkl. · ekstra 300 kr/år', digital_card_extra: 'Ikke understøttet', mobilepay: 'Ja',
        netbank: 'MitNykredit', payroll: 'Bank Connect inkl.', api: 'Ja (Bank Connect inkl.)', physical_branch: 'Ja',
        support: 'Dedikeret rådgiver, lokalbank',
                killer_features: [{"label":"10 konti/kort/brugere","tone":"blue"},{"label":"Bank Connect inkl.","tone":"green"},{"label":"Årlig revisorforespørgsel","tone":"neutral"},{"label":"Holding gratis","tone":"green"},{"label":"Pensions/forsikrings-tjek","tone":"neutral"}],
        extra_account_fee: 'Ubegrænset inkl.',
        overdraft: 'Ja', business_loan: 'Ja', credit_pricing: 'Realkredit-bidrag fra ~1,5% p.a. · ErhvervsKroner-rabat 1.500 kr/lånt mio. kr/år (til 2027).',
        _monthly: 385, _transfer: 1, _intl: 50, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
    ]
  },
];

// Sources (verified 2026-04-29): seb.se, swedbank.se, handelsbanken.se, nordea.se,
// dnb.no, nordea.no, sparebank1.no, op.fi, nordea.fi, aktia.fi, revolut.com, lunar.app.
// Lunar FI omitted (not yet launched). S-Pankki FI omitted (no SME accounts for new customers).
const BANKS_SE = [
  { id: 'danske_se', name: 'Danske Bank', color: '#0E2540', logo: 'DB',
    packages: [
      { name: 'Danske Företagspaket',
        onboarding: '2.500 SEK', monthly: 'Verify with bank (~250 SEK)', min_balance: '0 SEK',
        domestic_transfer: 'Inkl. i paket', intl_transfer: 'Verify with bank (SWIFT)', fx_fee: '1,17% EU / 1,99% övriga',
        card_fee: 'Mastercard Business inkl.', mobilepay: 'Swish Företag (separat)',
        netbank: 'District / Business app', payroll: 'Via Lönefil', api: 'Ja (District API)', physical_branch: 'Ja (Stockholm)',
        support: 'Telefon, chat, kontor',
        killer_features: [{label:'Nordisk universalbank',tone:'neutral'},{label:'District-platformen',tone:'blue'},{label:'Trade finance',tone:'gold'}],
        _monthly: 250, _transfer: 2, _intl: 70, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
    ]},
  { id: 'seb', name: 'SEB', color: '#5DAB45', logo: 'SEB',
    packages: [
      { name: 'Enkla firman',
        onboarding: '2.500 SEK', monthly: '100 SEK (6 mån gratis)', min_balance: '0 SEK',
        domestic_transfer: '1,85 SEK / Bg-utbet', intl_transfer: '50 SEK (SWIFT)', fx_fee: '2,0%',
        card_fee: 'SEB Commercial Debit 25 SEK/mån', mobilepay: 'Swish Företag 2,50 SEK/tx',
        netbank: 'SEB Företagsbanken / app', payroll: 'Via SEB Lönefil', api: 'Ja (Open Banking API)', physical_branch: 'Ja',
        support: 'Telefon, chat, kontor (vard. 8-18)',
        killer_features: [{label:'Storbank-tyngd',tone:'neutral'},{label:'6 mån gratis',tone:'green'},{label:'Greenhouse for Startups',tone:'blue'}],
        _monthly: 100, _transfer: 2, _intl: 50, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
      { name: 'Företagspaketet',
        onboarding: '2.500 SEK', monthly: '130 SEK (6 mån gratis)', min_balance: '0 SEK',
        domestic_transfer: '1,85 SEK / Bg-utbet', intl_transfer: '70 SEK (SWIFT)', fx_fee: '2,0%',
        card_fee: 'SEB Corporate Limit 450 SEK/år inkl.', mobilepay: 'Swish Företag 2,50 SEK/tx',
        netbank: 'SEB Företagsbanken / app', payroll: 'Via SEB Lönefil', api: 'Ja (Open Banking API)', physical_branch: 'Ja',
        support: 'Telefon, chat, kontor, dedikerad rådgivare',
        killer_features: [{label:'Corporate Limit-kort',tone:'gold'},{label:'Greenhouse-rabatter',tone:'blue'},{label:'Multi-currency',tone:'blue'},{label:'Trade finance',tone:'neutral'}],
        _monthly: 130, _transfer: 2, _intl: 70, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
    ]},
  { id: 'swedbank', name: 'Swedbank', color: '#FFCD00', logo: 'SW',
    packages: [
      { name: 'Företagspaket',
        onboarding: '2.500 SEK', monthly: '117 SEK', min_balance: '0 SEK',
        domestic_transfer: 'Bankgiro inkl., Swish 1,50 SEK/tx', intl_transfer: 'Verify with bank', fx_fee: 'Verify with bank',
        card_fee: '1 Business Debit + 1 Business Credit inkl.', mobilepay: 'Swish Företag 1,50 SEK/tx',
        netbank: 'Internetbanken Företag / app', payroll: 'Via Bg lönefil', api: 'Ja (Open Banking)', physical_branch: 'Ja (sparbanksnätet)',
        support: 'Telefon, chat, kontor, lokal sparbank',
        killer_features: [{label:'Sparbanksnätverket',tone:'neutral'},{label:'Swish 1,50 kr/tx',tone:'green'},{label:'10% rabatt försäkring',tone:'green'},{label:'2 kort inkl.',tone:'blue'}],
        _monthly: 117, _transfer: 2, _intl: 70, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
    ]},
  { id: 'handelsbanken', name: 'Handelsbanken', color: '#00529B', logo: 'SHB',
    packages: [
      { name: 'Företagspaketet',
        onboarding: 'Verify with bank', monthly: '160 SEK', min_balance: '0 SEK',
        domestic_transfer: 'Tillkommer separat', intl_transfer: 'Tillkommer separat', fx_fee: 'Verify with bank',
        card_fee: 'Företagskort kredit/debet (separat)', mobilepay: 'Swish Företag (separat)',
        netbank: 'Internet Företag / Företagsapp', payroll: 'Via filintegration', api: 'Ja (50+ tjänster)', physical_branch: 'Ja (lokal kontorsmodell)',
        support: 'Personlig kontorsrådgivare, telefon',
        killer_features: [{label:'Lokal kontorsmodell',tone:'gold'},{label:'Personlig rådgivare',tone:'gold'},{label:'50+ tjänster à la carte',tone:'neutral'}],
        _monthly: 160, _transfer: 3, _intl: 80, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
    ]},
  { id: 'nordea_se', name: 'Nordea', color: '#1100C8', logo: 'N',
    packages: [
      { name: 'Företagspaket',
        onboarding: '2.500 SEK', monthly: '108 SEK', min_balance: '0 SEK',
        domestic_transfer: 'Inkl. i paket, Swish 2 SEK/tx', intl_transfer: 'Verify with bank (SWIFT)', fx_fee: '1,17% EU / 1,99% övriga',
        card_fee: '1 Business Debit inkl.', mobilepay: 'Swish Företag',
        netbank: 'Nordea Business / app', payroll: 'Via partner', api: 'Ja (Nordea API Market)', physical_branch: 'Ja',
        support: 'Telefon, chat, filial (vard. 8:30-17)',
        killer_features: [{label:'Nordiskt nätverk',tone:'blue'},{label:'API Market',tone:'blue'},{label:'Best SME Platform 2025',tone:'gold'}],
        _monthly: 108, _transfer: 2, _intl: 200, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
    ]},
  { id: 'revolut_se', name: 'Revolut', color: '#191C1F', logo: 'R',
    packages: [
      { name: 'Basic',
        onboarding: '0 SEK', monthly: '0 SEK', min_balance: '0 SEK',
        domestic_transfer: '5 fria/mån', intl_transfer: 'Pay-as-you-go', fx_fee: '0,6% (1% helger)',
        card_fee: '1 fysiskt + 200 virtuella', mobilepay: 'Nej (ingen Swish-företag)',
        netbank: 'Revolut Business / app', payroll: '—', api: 'Begränsad', physical_branch: 'Nej',
        support: 'Chat 24/7',
        killer_features: [{label:'Ingen månadsavgift',tone:'green'},{label:'25+ valutor',tone:'blue'},{label:'~10 min onboarding',tone:'green'}],
        _monthly: 0, _transfer: 0, _intl: 0, _hasApi: false, _hasBranch: false, _hasMobilePay: false },
      { name: 'Grow',
        onboarding: '0 SEK', monthly: '400 SEK', min_balance: '0 SEK',
        domestic_transfer: '100 fria/mån', intl_transfer: '5 fria/mån', fx_fee: '0,6% (1% helger)',
        card_fee: '1 metal + 200 virtuella', mobilepay: 'Nej',
        netbank: 'Revolut Business / app', payroll: '—', api: 'Ja', physical_branch: 'Nej',
        support: 'Chat 24/7',
        killer_features: [{label:'100 fria överf.',tone:'blue'},{label:'5 SWIFT fria',tone:'blue'},{label:'Bulk payments',tone:'neutral'},{label:'Metal-kort',tone:'gold'}],
        _monthly: 400, _transfer: 0, _intl: 0, _hasApi: true, _hasBranch: false, _hasMobilePay: false },
      { name: 'Scale',
        onboarding: '0 SEK', monthly: '1.100 SEK', min_balance: '0 SEK',
        domestic_transfer: '1.000 fria/mån', intl_transfer: '25 fria/mån', fx_fee: '0,6% (1% helger)',
        card_fee: '2 metal + obegränsade virtuella', mobilepay: 'Nej',
        netbank: 'Revolut Business / app', payroll: '—', api: 'Ja', physical_branch: 'Nej',
        support: 'Prioritet chat 24/7',
        killer_features: [{label:'1.000 fria överf.',tone:'blue'},{label:'25 SWIFT fria',tone:'blue'},{label:'Hög FX-allowance',tone:'green'}],
        _monthly: 1100, _transfer: 0, _intl: 0, _hasApi: true, _hasBranch: false, _hasMobilePay: false },
    ]},
  { id: 'lunar_se', name: 'Lunar', color: '#1EC862', logo: 'L',
    packages: [
      { name: 'Lunar Business Simple',
        onboarding: '295 SEK', monthly: '89 SEK', min_balance: '0 SEK',
        domestic_transfer: 'Standardavgifter (Bg/Swish separat)', intl_transfer: 'Tillkommer (SWIFT)', fx_fee: '0,5%',
        card_fee: '1 digitalt Visa', mobilepay: 'Swish Företag (tillval)',
        netbank: 'Lunar app', payroll: '—', api: 'Begränsad', physical_branch: 'Nej',
        support: 'Chat, e-post (sv. supporttider)',
        killer_features: [{label:'Sveriges billigaste',tone:'green'},{label:'100% digitalt',tone:'blue'},{label:'Bra för holding',tone:'neutral'}],
        _monthly: 89, _transfer: 3, _intl: 50, _hasApi: false, _hasBranch: false, _hasMobilePay: true },
      { name: 'Lunar Business Essential',
        onboarding: '0 SEK', monthly: '119 SEK', min_balance: '0 SEK',
        domestic_transfer: 'Lägre tx-avgift än Simple', intl_transfer: 'Tillkommer (SWIFT)', fx_fee: '0,5%',
        card_fee: '3 fysiska + 3 digitala Visa', mobilepay: 'Swish Företag (tillval)',
        netbank: 'Lunar app', payroll: '—', api: 'Ja (bokföringsintegration)', physical_branch: 'Nej',
        support: 'Chat, e-post',
        killer_features: [{label:'3 konton + 6 kort',tone:'blue'},{label:'Auto-bokföring',tone:'blue'},{label:'Multi-currency Visa',tone:'green'},{label:'1,75% sparränta',tone:'green'}],
        _monthly: 119, _transfer: 2, _intl: 50, _hasApi: true, _hasBranch: false, _hasMobilePay: true },
    ]},
];

const BANKS_NO = [
  { id: 'danske_no', name: 'Danske Bank', color: '#0E2540', logo: 'DB',
    packages: [
      { name: 'Danske Bedriftspakke',
        onboarding: 'Verify with bank', monthly: 'Verify with bank (~250 NOK)', min_balance: '0 NOK',
        domestic_transfer: 'Inkl. i pakken', intl_transfer: 'Verify with bank (SWIFT)', fx_fee: '0,4-1,0%',
        card_fee: '1 Mastercard Business inkl.', mobilepay: 'Vipps Bedrift (separat)',
        netbank: 'District / Business app', payroll: 'Via lønnsfil', api: 'Ja (District API)', physical_branch: 'Ja (Oslo)',
        support: 'Telefon, chat, kontor',
        killer_features: [{label:'Nordisk universalbank',tone:'neutral'},{label:'District-platform',tone:'blue'},{label:'Trade finance',tone:'gold'}],
        _monthly: 250, _transfer: 3, _intl: 75, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
    ]},
  { id: 'dnb', name: 'DNB', color: '#007272', logo: 'DNB',
    packages: [
      { name: 'DNB Bedriftspakke (Start)',
        onboarding: '0 NOK', monthly: '149 NOK (gratis første år)', min_balance: '0 NOK',
        domestic_transfer: 'Inkl. i pakken (nettbank)', intl_transfer: 'Verify with bank (SWIFT)', fx_fee: 'Verify with bank',
        card_fee: '1 bedriftskort inkl.', mobilepay: 'Vipps Bedrift (separat)',
        netbank: 'DNB Bedrift / app', payroll: 'Via DNB Regnskap', api: 'Ja (Open Banking)', physical_branch: 'Ja',
        support: 'Telefon, chat, kontor, dedikert rådgiver',
        killer_features: [{label:'Norges største bank',tone:'gold'},{label:'Gratis første år',tone:'green'},{label:'DNB Regnskap inkl.',tone:'blue'},{label:'Vipps integrasjon',tone:'neutral'}],
        _monthly: 149, _transfer: 4, _intl: 75, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
      { name: 'DNB Regnskap Pluss',
        onboarding: '0 NOK', monthly: '249 NOK', min_balance: '0 NOK',
        domestic_transfer: 'Inkl. i pakken', intl_transfer: 'Verify with bank', fx_fee: 'Verify with bank',
        card_fee: '1 bedriftskort inkl.', mobilepay: 'Vipps Bedrift',
        netbank: 'DNB Bedrift / app', payroll: 'Inkl. lønnsmodul', api: 'Ja (full DNB Regnskap)', physical_branch: 'Ja',
        support: 'Telefon, chat, kontor',
        killer_features: [{label:'Lønn inkl.',tone:'green'},{label:'Faktura inkl.',tone:'blue'},{label:'Filialnett',tone:'neutral'}],
        _monthly: 249, _transfer: 4, _intl: 75, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
    ]},
  { id: 'nordea_no', name: 'Nordea', color: '#1100C8', logo: 'N',
    packages: [
      { name: 'Nordea Start',
        onboarding: 'Verify with bank', monthly: '139 NOK', min_balance: '0 NOK',
        domestic_transfer: 'Mellom egne konti 50 NOK', intl_transfer: '75-350 NOK', fx_fee: '0,4-1,0% valutapåslag',
        card_fee: 'Visa Business 590 NOK/år', mobilepay: 'Vipps Bedrift (separat)',
        netbank: 'Nordea Business / app', payroll: 'Via partner', api: 'Ja (Nordea API Market)', physical_branch: 'Ja',
        support: 'Telefon, chat, filial',
        killer_features: [{label:'Nordisk nettverk',tone:'blue'},{label:'API Market',tone:'blue'},{label:'Best SME Platform 2025',tone:'gold'}],
        _monthly: 139, _transfer: 3, _intl: 75, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
      { name: 'Nordea Plus',
        onboarding: 'Verify with bank', monthly: '159 NOK', min_balance: '0 NOK',
        domestic_transfer: 'Inkl. flere fria overføringer', intl_transfer: '75-350 NOK', fx_fee: '0,4-1,0%',
        card_fee: '1 Visa Business inkl.', mobilepay: 'Vipps Bedrift',
        netbank: 'Nordea Business / app', payroll: 'Via partner', api: 'Ja (Nordea API Market)', physical_branch: 'Ja',
        support: 'Telefon, chat, filial',
        killer_features: [{label:'Inntil 3 konti inkl.',tone:'blue'},{label:'Visa Business inkl.',tone:'green'},{label:'Multi-currency',tone:'blue'}],
        _monthly: 159, _transfer: 2, _intl: 75, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
    ]},
  { id: 'sparebank1', name: 'SpareBank 1', color: '#E60000', logo: 'SB1',
    packages: [
      { name: 'Nettbank Bedrift Basis',
        onboarding: '0 NOK', monthly: '95 NOK (0 NOK for ENK)', min_balance: '0 NOK',
        domestic_transfer: 'KID 1,75 NOK / strukt. 5,50 NOK', intl_transfer: 'SEPA 5,50 NOK / valuta 75 NOK', fx_fee: '2,0%',
        card_fee: 'Visa Business 300 NOK/år + 3 NOK/tx', mobilepay: 'Vipps Bedrift',
        netbank: 'SpareBank 1 Bedrift / app', payroll: 'Via lønnsfil', api: 'Ja (Open Banking)', physical_branch: 'Ja (regionalt nett)',
        support: 'Telefon, chat, lokalt kontor',
        killer_features: [{label:'Gratis for ENK',tone:'green'},{label:'Lokalbank-nettverk',tone:'gold'},{label:'KID 1,75 NOK',tone:'green'}],
        _monthly: 95, _transfer: 3, _intl: 75, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
    ]},
  { id: 'revolut_no', name: 'Revolut', color: '#191C1F', logo: 'R',
    packages: [
      { name: 'Basic',
        onboarding: '0 NOK', monthly: '0 NOK', min_balance: '0 NOK',
        domestic_transfer: '5 fria/mnd', intl_transfer: 'Pay-as-you-go', fx_fee: '0,6% (1% helger)',
        card_fee: '1 fysisk + 200 virtuelle', mobilepay: 'Nei (ingen Vipps)',
        netbank: 'Revolut Business / app', payroll: '—', api: 'Begrenset', physical_branch: 'Nei',
        support: 'Chat 24/7',
        killer_features: [{label:'Ingen månedspris',tone:'green'},{label:'25+ valutaer',tone:'blue'},{label:'~10 min onboarding',tone:'green'}],
        _monthly: 0, _transfer: 0, _intl: 0, _hasApi: false, _hasBranch: false, _hasMobilePay: false },
      { name: 'Grow',
        onboarding: '0 NOK', monthly: '400 NOK', min_balance: '0 NOK',
        domestic_transfer: '100 fria/mnd', intl_transfer: '5 fria/mnd', fx_fee: '0,6% (1% helger)',
        card_fee: '1 metal + 200 virtuelle', mobilepay: 'Nei',
        netbank: 'Revolut Business / app', payroll: '—', api: 'Ja', physical_branch: 'Nei',
        support: 'Chat 24/7',
        killer_features: [{label:'100 fria overf.',tone:'blue'},{label:'5 SWIFT fria',tone:'blue'},{label:'Metal-kort',tone:'gold'}],
        _monthly: 400, _transfer: 0, _intl: 0, _hasApi: true, _hasBranch: false, _hasMobilePay: false },
      { name: 'Scale',
        onboarding: '0 NOK', monthly: '1.100 NOK', min_balance: '0 NOK',
        domestic_transfer: '1.000 fria/mnd', intl_transfer: '25 fria/mnd', fx_fee: '0,6% (1% helger)',
        card_fee: '2 metal + ubegrensede virtuelle', mobilepay: 'Nei',
        netbank: 'Revolut Business / app', payroll: '—', api: 'Ja', physical_branch: 'Nei',
        support: 'Prioritet chat 24/7',
        killer_features: [{label:'1.000 fria overf.',tone:'blue'},{label:'25 SWIFT fria',tone:'blue'},{label:'Høy FX-allowance',tone:'green'}],
        _monthly: 1100, _transfer: 0, _intl: 0, _hasApi: true, _hasBranch: false, _hasMobilePay: false },
    ]},
  { id: 'lunar_no', name: 'Lunar', color: '#1EC862', logo: 'L',
    packages: [
      { name: 'Lunar Business Solo',
        onboarding: '0 NOK', monthly: '69 NOK', min_balance: '0 NOK',
        domestic_transfer: 'Inkl. i pakken', intl_transfer: 'Tilkommer (SWIFT)', fx_fee: '0,5% (+1% utenlandskjøp)',
        card_fee: '1 Visa + 1 digitalt', mobilepay: 'Vipps Bedrift (tillval)',
        netbank: 'Lunar app', payroll: '—', api: 'Visma-integrasjon', physical_branch: 'Nei',
        support: 'Norsk chat, telefon, e-post',
        killer_features: [{label:'Norges billigste ENK',tone:'green'},{label:'3% rente opp til 1M',tone:'green'},{label:'Cyber + reise-forsikring',tone:'blue'},{label:'Kun for ENK',tone:'neutral'}],
        _monthly: 69, _transfer: 2, _intl: 50, _hasApi: true, _hasBranch: false, _hasMobilePay: true },
    ]},
];

const BANKS_FI = [
  { id: 'danske_fi', name: 'Danske Bank', color: '#0E2540', logo: 'DB',
    packages: [
      { name: 'Danske yrityspaketti',
        onboarding: 'Verify with bank', monthly: 'Verify with bank (~15 €)', min_balance: '0 €',
        domestic_transfer: 'SEPA Verify with bank', intl_transfer: 'Verify with bank (SWIFT)', fx_fee: 'Verify with bank',
        card_fee: 'Business Mastercard (lisämaksu)', mobilepay: 'MobilePay yrityksille',
        netbank: 'District / Business app', payroll: 'Integraatio', api: 'Ja (District API)', physical_branch: 'Ja (Helsinki)',
        support: 'Puhelin, chat, konttori',
        killer_features: [{label:'Pohjoismainen universaalipankki',tone:'neutral'},{label:'District-alusta',tone:'blue'},{label:'Trade finance',tone:'gold'}],
        _monthly: 15, _transfer: 0.30, _intl: 7, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
    ]},
  { id: 'op', name: 'OP Ryhmä', color: '#FF6600', logo: 'OP',
    packages: [
      { name: 'OP yritystili (perus)',
        onboarding: '100 €', monthly: '12,90 €', min_balance: '0 €',
        domestic_transfer: 'SEPA 0,24 €', intl_transfer: '6 € (muut valuutat)', fx_fee: 'Visa/MC +1,95% kortilla',
        card_fee: 'OP Visa Business ~33 €/v', mobilepay: 'Pivo Yritys',
        netbank: 'OP-yritysmobiili + op.fi', payroll: 'Lähitapiola/integraatio', api: 'Ja (Open Banking)', physical_branch: 'Ja (osuuspankit)',
        support: 'Puhelin, chat, konttori',
        killer_features: [{label:'Suomen suurin pankki',tone:'gold'},{label:'Osuuskaupan asiakasedut',tone:'green'},{label:'Pivo Yritys',tone:'blue'},{label:'180+ konttoria',tone:'neutral'}],
        _monthly: 13, _transfer: 0.24, _intl: 6, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
      { name: 'OP yritystili (yrittäjä)',
        onboarding: '100 €', monthly: '11,55 €', min_balance: '0 €',
        domestic_transfer: 'SEPA 0,24 €', intl_transfer: '6 €', fx_fee: '+1,95% kortti-FX',
        card_fee: 'OP Visa Business sis.', mobilepay: 'Pivo Yritys',
        netbank: 'OP-yritysmobiili', payroll: '—', api: 'Ja', physical_branch: 'Ja',
        support: 'Puhelin, chat, konttori',
        killer_features: [{label:'Yksityisyrittäjille',tone:'blue'},{label:'Edullisin OP-paketti',tone:'green'},{label:'Konttoriverkosto',tone:'neutral'}],
        _monthly: 11.55, _transfer: 0.24, _intl: 6, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
    ]},
  { id: 'nordea_fi', name: 'Nordea', color: '#1100C8', logo: 'N',
    packages: [
      { name: 'Nordea Digital -palvelupaketti',
        onboarding: '0 €', monthly: '15,70 €', min_balance: '0 €',
        domestic_transfer: 'SEPA 0,23 € / saapuva 0,15 €', intl_transfer: '7,00 €', fx_fee: '2,25% (ei EUR/SEK)',
        card_fee: 'Business Visa Debit sis.', mobilepay: 'MobilePay yrityksille',
        netbank: 'Nordea Business + verkkopankki', payroll: 'eLasku + integraatiot', api: 'Ja (Nordea API Market)', physical_branch: 'Ja',
        support: 'Puhelin, chat, konttori',
        killer_features: [{label:'Pohjoismainen verkosto',tone:'blue'},{label:'API Market',tone:'blue'},{label:'eLasku sis.',tone:'green'},{label:'Visa Debit sis.',tone:'green'}],
        _monthly: 15.70, _transfer: 0.23, _intl: 7, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
      { name: 'Nordea Business verkkopankki',
        onboarding: '0 €', monthly: '7,50 €', min_balance: '0 €',
        domestic_transfer: 'SEPA 0,23 €', intl_transfer: '7,00 €', fx_fee: '2,25%',
        card_fee: 'Business Visa Debit 40 €/v', mobilepay: 'MobilePay',
        netbank: 'Nordea Business', payroll: 'Integraatio', api: 'Ja', physical_branch: 'Ja',
        support: 'Puhelin, chat',
        killer_features: [{label:'Edullinen perustaso',tone:'green'},{label:'Skaalautuu lisäkäyttäjillä',tone:'blue'},{label:'Pohjoismainen verkosto',tone:'neutral'}],
        _monthly: 7.50, _transfer: 0.23, _intl: 7, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
    ]},
  { id: 'aktia', name: 'Aktia', color: '#005EB8', logo: 'A',
    packages: [
      { name: 'Aktia yritystili',
        onboarding: '150 €', monthly: '~15 € (palvelutaso)', min_balance: '0 €',
        domestic_transfer: 'Verify with bank', intl_transfer: 'Verify with bank', fx_fee: 'Verify with bank',
        card_fee: 'Business Debit (lisämaksu)', mobilepay: 'MobilePay yrityksille',
        netbank: 'Aktia verkkopankki + mobiili', payroll: 'Integraatio', api: 'Ja (Open Banking)', physical_branch: 'Ja (rajatut konttorit)',
        support: 'Puhelin, chat',
        killer_features: [{label:'Suomalainen omistus',tone:'gold'},{label:'Henkilökohtainen palvelu',tone:'blue'},{label:'Talletussuoja 100 k€',tone:'green'}],
        _monthly: 15, _transfer: 0.30, _intl: 8, _hasApi: true, _hasBranch: true, _hasMobilePay: true },
    ]},
  { id: 'revolut_fi', name: 'Revolut', color: '#191C1F', logo: 'R',
    packages: [
      { name: 'Basic',
        onboarding: '0 €', monthly: '0 €', min_balance: '0 €',
        domestic_transfer: '5 ilmaista/kk', intl_transfer: 'Pay-as-you-go', fx_fee: '0,6% (1% vkl)',
        card_fee: '1 fyysinen + 200 virtuaalista', mobilepay: 'Ei (ei MobilePay)',
        netbank: 'Revolut Business / app', payroll: '—', api: 'Rajoitettu', physical_branch: 'Ei',
        support: 'Chat 24/7',
        killer_features: [{label:'Ei kuukausimaksua',tone:'green'},{label:'25+ valuuttaa',tone:'blue'},{label:'~10 min onboarding',tone:'green'}],
        _monthly: 0, _transfer: 0, _intl: 0, _hasApi: false, _hasBranch: false, _hasMobilePay: false },
      { name: 'Grow',
        onboarding: '0 €', monthly: '30 €', min_balance: '0 €',
        domestic_transfer: '100 ilmaista/kk', intl_transfer: '5 ilmaista/kk', fx_fee: '0,6% (1% vkl)',
        card_fee: '1 metal + 200 virtuaalista', mobilepay: 'Ei',
        netbank: 'Revolut Business / app', payroll: '—', api: 'Kyllä', physical_branch: 'Ei',
        support: 'Chat 24/7',
        killer_features: [{label:'100 ilmaista siirtoa',tone:'blue'},{label:'5 SWIFT ilmaista',tone:'blue'},{label:'10 000 € FX-vapaa',tone:'green'},{label:'Metal-kortti',tone:'gold'}],
        _monthly: 30, _transfer: 0, _intl: 0, _hasApi: true, _hasBranch: false, _hasMobilePay: false },
      { name: 'Scale',
        onboarding: '0 €', monthly: '90 €', min_balance: '0 €',
        domestic_transfer: '1 000 ilmaista/kk', intl_transfer: '25 ilmaista/kk', fx_fee: '0,6% (1% vkl)',
        card_fee: '2 metal + rajattomat virtuaaliset', mobilepay: 'Ei',
        netbank: 'Revolut Business / app', payroll: '—', api: 'Kyllä', physical_branch: 'Ei',
        support: 'Priorisoitu chat 24/7',
        killer_features: [{label:'1 000 ilmaista siirtoa',tone:'blue'},{label:'25 SWIFT ilmaista',tone:'blue'},{label:'Korkea FX-vapaa',tone:'green'}],
        _monthly: 90, _transfer: 0, _intl: 0, _hasApi: true, _hasBranch: false, _hasMobilePay: false },
    ]},
];

const COUNTRY_BANKS = { DK: BANKS_DK, SE: BANKS_SE, NO: BANKS_NO, FI: BANKS_FI };

const EXTRA_BANKS = [
  { id: 'jyske', name: 'Jyske Bank', color: '#C85000', logo: 'JB' },
  { id: 'sydbank', name: 'Sydbank', color: '#004B6E', logo: 'SB' },
  { id: 'sparekassen', name: 'Sparekassen Danmark', color: '#8B0000', logo: 'SD' },
  { id: 'andelskassen', name: 'Andelskassen', color: '#2D6A4F', logo: 'AK' },
];

// Quiz scoring function
const mid = v => Array.isArray(v) ? (v[0] + v[1]) / 2 : v;
function scorePackage(pkg, answers) {
  let score = 100;
  const { needsIntl, needsBranch, needsApi, needsPayroll } = answers;
  const txMonth = mid(answers.txMonth) ?? 30;
  const budget = mid(answers.budget) ?? 1000;
  // Monthly cost
  const totalCost = pkg._monthly + (txMonth * pkg._transfer) + (needsIntl ? pkg._intl * 5 : 0);
  if (totalCost > budget) score -= 40;
  else score += (budget - totalCost) / budget * 20;
  // Branch
  if (needsBranch && !pkg._hasBranch) score -= 50;
  if (!needsBranch && !pkg._hasBranch) score += 5;
  // API
  if (needsApi && !pkg._hasApi) score -= 20;
  if (needsApi && pkg._hasApi) score += 15;
  // Payroll
  if (needsPayroll && pkg.payroll === '—') score -= 20;
  // International
  if (needsIntl && pkg._intl > 30) score -= 10;
  if (needsIntl && pkg._intl === 0) score += 15;
  return Math.max(0, Math.round(score));
}

Object.assign(window, { COUNTRIES, ROW_GROUPS, BANKS_DK, COUNTRY_BANKS, EXTRA_BANKS, scorePackage, DATA_LAST_UPDATED });
